// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_n9YCQwdg63S2FOA8e2Zo3RclsGNj56M',
    appId: '1:446250056140:web:30dceea4c50eec96754569',
    messagingSenderId: '446250056140',
    projectId: 'my-data-app-451a8',
    authDomain: 'my-data-app-451a8.firebaseapp.com',
    storageBucket: 'my-data-app-451a8.firebasestorage.app',
    measurementId: 'G-MHEE3QYRPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEA_6tynwhJvWKGmm1QTesdCVWjGsc7PI',
    appId: '1:446250056140:android:24cf269eaae717ca754569',
    messagingSenderId: '446250056140',
    projectId: 'my-data-app-451a8',
    storageBucket: 'my-data-app-451a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf8rx_TBwLacitWXhNJVRh60A7_ESXg_w',
    appId: '1:446250056140:ios:2e007cbae8b8efc8754569',
    messagingSenderId: '446250056140',
    projectId: 'my-data-app-451a8',
    storageBucket: 'my-data-app-451a8.firebasestorage.app',
    iosBundleId: 'com.example.myDataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf8rx_TBwLacitWXhNJVRh60A7_ESXg_w',
    appId: '1:446250056140:ios:2e007cbae8b8efc8754569',
    messagingSenderId: '446250056140',
    projectId: 'my-data-app-451a8',
    storageBucket: 'my-data-app-451a8.firebasestorage.app',
    iosBundleId: 'com.example.myDataApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_n9YCQwdg63S2FOA8e2Zo3RclsGNj56M',
    appId: '1:446250056140:web:f4d9f00625d11776754569',
    messagingSenderId: '446250056140',
    projectId: 'my-data-app-451a8',
    authDomain: 'my-data-app-451a8.firebaseapp.com',
    storageBucket: 'my-data-app-451a8.firebasestorage.app',
    measurementId: 'G-V558DPWH1K',
  );
}
